### ISSUE TITLE
flyout menu unusable - vanishes too quickly

### ISSUE THREAD

**Issue by Kherae** [cjayride/CraftingFilter_Fork#1]
since a recent update, the flyout menu for selecting category vanishes the instant the mouse is off of any button, making it unusable

**Comment by cjayride** [comment]
sorry for the delay, had a significant life change. looking into this issue now

**Comment by cjayride** [comment]
Just ran a test. The flyout menu works in fullscreen mode, and window mode maximized.

I remember in previous versions, there was a issue with the menu vanishing too quickly.  It looks like this issue was resolved in CraftingFilter v1.1.0 by cjayride

[https://github.com/cjayride/CraftingFilter_Fork/releases/tag/v1.1.0](https://github.com/cjayride/CraftingFilter_Fork/releases/tag/v1.1.0)

**Comment by cjayride** [comment]
Can re-open issue if it's still an issue, but working okay on my end for now.

**Comment by cjayride** [comment]
Can re-open issue if it's still an issue, but working okay on my end for now.
